version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_transactions_api
    container_name: test_transactions_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
